### ISSUE TITLE
Подвисания при проигрывании звуков.

### ISSUE THREAD

**Issue by Starastel** [TrueCat17/Ren-Engine#2]
### Суть:
При проигрывании звуков игра (далее движок) стопорится на несколько миллисекунд. Я много раз переконвертировал весь игровой звук. Даже придя к выводу, что быстрее всего декодируется mp3, и, соответственно, после полного переконвертирования игрового звука подвисания всё равно не прекратились. Хотя, при этом, мне кажется, что их частота уменьшилась. Да и сами они, по большей части появляются при холодном старте. Но, так как эти звуки - внутриигровая озвучка, эти подвисания - явление довольно таки частое. 

### Возможная проблема (это исключительно мои домыслы):
Мне кажется, что эта проблема находится на уровне **FFmpeg'а**, так-как даже **при воспроизведении wav-файлов** (для этого я самостоятельно собрал движок) **подвисания не пропали**. Хотя эффект, вроде как должен был быть обратным. Периодичность их, кстати, примерно такая же.

Некоторые движки на основе SDL используют SDL_mixer для воспроизведения звука. Например VVVVVV, World Of Goo, System Shock EE их именно и используют. И там нет никаких подвисаний. Да и с недавнего времени SDL_mixer также стал поддерживать opus. Хотя **SDL Mixer X** это умел делать довольно таки давно. Да и сам он по функционалу будет по продвинутее чем обычный. Поэтому, возможно, SDL Mixer X будет лучше.

Но я не утверждаю, и возможно, проблема в чём-то другом. Да и я уверен, что у вас была веская причина использовать FFmpeg заместо более специализированной библиотеки.

**Comment by Starastel** [comment]
Отбой. Я вроде бы нашёл решение. В файле **music.cpp** я просто поправил
`wantedSpec.samples = 0;` на
`wantedSpec.samples = 4096;`
После этого подвисания при проигрывании звука полностью пропали. Даже wav-файлы стали работать отлично. Хотя у меня и осталось одно место где при холодном игра всё равно стопорится решением я, в целом, доволен. Тема закрыта. Спасибо.

**Comment by TrueCat17** [comment]
Насколько я понимаю, при указании  
`wantedSpec.freq = 44100;`  
samples устанавливается в 2048, что вроде не так уж и мало  
Впрочем, возможно, установка в 4096 вручную - всё же хорошая идея
