### ISSUE TITLE
Зацикливание звуков/музыки.

### ISSUE THREAD

**Issue by Starastel** [TrueCat17/Ren-Engine#3]
При попытке зациклить какой-нибудь звук, который в конце воспроизведения не "исчезает", слышны разрывы. На разных форматах они чуть-чуть отличаются.
Например [mp3](https://stateler.ml/Pages/SE02_11L_mp3_test.mp3), ogg и, на моей памяти, wav звучит одинакового. У [Opus](https://stateler.ml/Pages/SE02_11L_opus_test.mp3) разрывы очень даже ярко выражены. Вот, кстати, [оригинал](https://stateler.ml/Pages/SE02_11L.opus).

Мне исследование исходников и сборка ffmpeg'а с разными параметрами компиляции не помогло (да и ждать по пол часа на его сборку у меня желания уже нет). Догадок у меня тоже нет. Хотя я заметил, что shared версия ffmpeg'a у меня загружается и работает быстрее. Может стоит попробовать заставить движок работать, как минимум на Windows, с динамическими библиотеками, а не статическими. Во всяком случае - у меня пока не получилось.

**Comment by TrueCat17** [comment]
Для начала: ffmpeg собирается менее чем за 2 минуты (допускаю, что на слабых компьютерах мб и 5 минут)
Вы явно делаете что-то не так, если сборка занимает так много времени
Возможно, вы пересобираете все зависимости Ren-Engine, или если собираете ffmpeg где-то отдельно, то забываете отключить все ненужные компоненты

По сути вопроса отвечу чуть позже

**Comment by TrueCat17** [comment]
Вроде пофиксил
Проблема была на стороне Ren-Engine (даже 2 проблемы)
Пересборка ffmpeg не могла бы помочь

**Comment by Starastel** [comment]
Я проверил. На mp3 и ogg разрывы полностью пропали. На [opus](https://stateler.ml/Pages/SE02_11L_opus.mp3) - нет. Хотя и этот _**очень**_ приятный щелчок пропал. 
Во всяком случае - спасибо за исправление.
И да, я пересобирал все зависимости.

**Comment by TrueCat17** [comment]
Надеюсь, теперь точно всё

Пересобирать все зависимости нет смысла
Логичнее зайти в папку с исходниками ffmpeg (т. е. что-то вроде libs/sources/ffmpeg/), подредактировать conf.sh, и после сохранения запустить команды
`./conf.sh 1>conf_out.txt 2>conf_err.txt`  
для конфигурирования и
`./make.sh 1>make_out.txt 2>make_err.txt`  
для сборки

И кстати, ogg - это контейнер, а не формат
Формат - vorbis
opus тоже хранится в контейнере ogg, не смотря на то, что расширение файлу можно поставить какое-угодно, в том числе и opus (в принципе, тот же mp3 тоже можно переименовать в opus, но структура файла от этого не поменяется)

**Comment by Starastel** [comment]
Про сборку учту, спасибо.
Разрывы теперь полностью пропали. 
Единственное, у меня, почему-то, перестал работать `renpy.music.set_volume`.
Выдаёт такую ошибку:
```
Python Error (<type 'exceptions.NameError'>):
	global name '_set_volume' is not defined
Traceback:
  File "mods/test/main.rpy", line 7, in <module>
    $ snd_loop('SE02_11L', 100, 0)
  File "mods/common/aditional.rpy", line 135, in snd_loop
    renpy.music.set_volume((vlm * 0.01), "snd_loop")
  File "../Ren-Engine/rpy/renpy_api.rpy", line 34, in renpy__music__set_volume
    _set_volume(in_bounds(vol, 0, 1), channel, file_name, num_line)

Code:
snd_loop('SE02_11L', 100, 0)
```
У функции такой код:
```Python
...
    def snd_loop(name, vlm, fd):
        play_sound = 'sound/sfx/' + name + '.opus'
        renpy.music.set_volume((vlm * 0.01), "snd_loop")
        renpy.play(play_sound, 'snd_loop', fadein = fd)
...
```

**Comment by TrueCat17** [comment]
Файлы в Ren-Engine/rpy/ нужно тоже обновлять, не только в src/

**Comment by Starastel** [comment]
Ай. Чёрт. Не заметил ;)
Мне просто немного боязно обновлять что-либо в rpy.
А так да, теперь всё работает.
