### ISSUE TITLE
Изменение громкости аудио при его проигрывании в сценарии.

### ISSUE THREAD

**Issue by Starastel** [TrueCat17/Ren-Engine#4]
В `renpy.music.play` файла `renpy_api.py` я добавил:
```Python
volume = kwargs.get('volume', 1)
renpy.music.set_volume(volume, channel)
```
Теперь при воспроизведении аудио из кода можно указать громкость канала:
```Python
renpy.play(sea_waves, 'sound_loop', volume = 0.2)
```
А вот в сценарии вот такой код не работает:
```Ren'Py
play sound_loop sea_waves volume 0.2
```
Движок гласит следующее:
```
Music::play Error:
3 argument must be <fadein>

File <mods/ever17/script/op.rpy>
Line 17: <sound_loop SE09_01L volume 0.2>
```

**Comment by TrueCat17** [comment]
Так-то и не предполагалось, что это должно работать
Впрочем, в renpy это рабочая конструкция, так что нужно будет реализовать

**Comment by TrueCat17** [comment]
Сделано
Кстати, `renpy.music.play` принимает `relative_volume`, а не `volume`

**Comment by Starastel** [comment]
Ясно. Спасибо. Всё шикарно работает.
